### ISSUE TITLE
Restructuring site index to contextualise GDPR additions

### ISSUE THREAD

**Issue by jsheunis** [CPernet/open-brain-consent#4]
Hi everyone. I'm working on reviewing and updating the docs that were added relating to GDPR. I'm realising that I personally don't like the structure of the index / sidebar as it is currently. There are two things I would like to change:

1. The structure and order of files/headings/subheadings for GDPR specific content that we are adding to the site.
2. The structure and order of files/headings/subheadings of the whole site.

I am ignoring the latter for now, since I think that's something we should first discuss with the group of people who created the site (e.g. by creating a separate issue + pull request).

With our latest updates to the GLiMR branch, the current index is ordered as follows:
```bash
open-brain-consent
.
|____Sample consent forms
|____Recommendations
|____Discussions
|____Ultimate consent form
| |____Single access
| |____Two access
|____Ultimate consent form - GDPR edition
| |____all of the subsections...
|____Anonymization tools
|____Contribute
|____Contact information
|____Data user agreement template
| |____General considerations
| |____DUA template
```
I propose that we bring in some of the structure that I depicted graphically [here](https://github.com/CPernet/open-brain-consent/issues/2#issuecomment-567427579), and also that we add some more paragraphs on the context for all the GDPR-related additions.

My working idea is something like this:
```bash
open-brain-consent
.
|____Sample consent forms
|____Recommendations
|____Discussions
|____Ultimate consent form
| |____Single access
| |____Two access
|____Ultimate consent form - GDPR edition
| |____Context
| |____Summary of GDPR-related additions
| |____Template
| | |____all of the subsections...
|____Data privacy impact assessment
| |____General considerations
| |____DPIA template
|____Data user agreement template
| |____General considerations
| |____DUA template
|____Anonymization tools
|____Contribute
|____Contact information
```
I've started working on a PR for this. In the mean time, please add your thoughts and suggestions here.

**Comment by CPernet** [comment]
happy with that - it is more ordered indeed 
I'd like to get @yarikoptic input too, no point merging here if on the main page it won't be accepted

**Comment by jsheunis** [comment]
Closing this to get it off my list of open issues :)
